=== teamfisk/TacticalZ/resources/Schema/Components/AssaultWeapon.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:t="types">
	<xs:import schemaLocation="../Types.xsd" namespace="types"/>

	<xs:element name="AssaultWeapon">
		<xs:complexType>
			<xs:all>
				<xs:element name="MagazineAmmo" type="t:int" minOccurs="0">
					<xs:annotation><xs:documentation>Ammo currently loaded into the magazine</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="MagazineSize" type="t:int" minOccurs="0">
									<xs:annotation><xs:documentation>Max number of rounds in a magazine</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="Ammo" type="t:int" minOccurs="0">
									<xs:annotation><xs:documentation>Current ammo carried</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="MaxAmmo" type="t:int" minOccurs="0">
									<xs:annotation><xs:documentation>Maximum ammo able to be carried</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="BaseDamage" type="t:double" minOccurs="0"/>
				<xs:element name="RPM" type="t:double" minOccurs="0">
					<xs:annotation><xs:documentation>Rate of fire in rounds per minute</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="ViewPunch" type="t:float" minOccurs="0">
					<xs:annotation><xs:documentation>View punch in radians for each bullet fired</xs:documentation></xs:annotation>
				</xs:element>
				<xs:element name="ReloadTime" type="t:double" minOccurs="0">
					<xs:annotation><xs:documentation>Time it takes to reload the weapon in seconds</xs:documentation></xs:annotation>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== teamfisk/TacticalZ/resources/Schema/Components/AssaultWeapon.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<AssaultWeapon xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AssaultWeapon.xsd">
	<MagazineAmmo>32</MagazineAmmo>
	<MagazineSize>32</MagazineSize>
	<Ammo>360</Ammo>
	<MaxAmmo>360</MaxAmmo>
	<BaseDamage>5</BaseDamage>
	<RPM>120</RPM>
	<ViewPunch>0.01</ViewPunch>
	<ReloadTime>2</ReloadTime>
</AssaultWeapon>
